-- Standard-Haushaltseinheiten für die geseedete Zutatenliste.
-- Idempotent: kann jederzeit erneut ausgeführt werden.
-- Faktor = wie viele Speicher-Einheiten 1× dieser Label sind.
-- Beispiel: Karotte (Speicher: g), Stück = 80 → 1 Stück = 80 g.

with mapping(name, label, factor, sort_order) as (values
  -- Gemüse: Stück-Gewichte und Bund-Gewichte
  ('Karotte', 'Stück', 80::numeric, 1),
  ('Karotte', 'Bund', 250::numeric, 2),
  ('Zwiebel', 'Stück', 110::numeric, 1),
  ('Rote Zwiebel', 'Stück', 110::numeric, 1),
  ('Knoblauch', 'Zehe', 5::numeric, 1),
  ('Knoblauch', 'Knolle', 50::numeric, 2),
  ('Kartoffel', 'Stück', 150::numeric, 1),
  ('Süßkartoffel', 'Stück', 200::numeric, 1),
  ('Tomate', 'Stück', 120::numeric, 1),
  ('Cherrytomaten', 'Stück', 15::numeric, 1),
  ('Cherrytomaten', 'Schale', 250::numeric, 2),
  ('Gurke', 'Stück', 300::numeric, 1),
  ('Paprika rot', 'Stück', 150::numeric, 1),
  ('Paprika gelb', 'Stück', 150::numeric, 1),
  ('Paprika grün', 'Stück', 150::numeric, 1),
  ('Zucchini', 'Stück', 200::numeric, 1),
  ('Aubergine', 'Stück', 250::numeric, 1),
  ('Brokkoli', 'Kopf', 400::numeric, 1),
  ('Blumenkohl', 'Kopf', 600::numeric, 1),
  ('Spinat frisch', 'Bund', 200::numeric, 1),
  ('Kopfsalat', 'Kopf', 300::numeric, 1),
  ('Rucola', 'Bund', 100::numeric, 1),
  ('Feldsalat', 'Bund', 100::numeric, 1),
  ('Lauch', 'Stange', 200::numeric, 1),
  ('Frühlingszwiebel', 'Stange', 15::numeric, 1),
  ('Frühlingszwiebel', 'Bund', 100::numeric, 2),
  ('Sellerieknolle', 'Stück', 700::numeric, 1),
  ('Stangensellerie', 'Stange', 60::numeric, 1),
  ('Pastinake', 'Stück', 150::numeric, 1),
  ('Rote Bete', 'Stück', 150::numeric, 1),
  ('Kürbis Hokkaido', 'Stück', 1500::numeric, 1),
  ('Champignons', 'Stück', 20::numeric, 1),
  ('Champignons', 'Schale', 250::numeric, 2),
  ('Ingwer', 'Daumen', 30::numeric, 1),
  ('Ingwer', 'Stück', 30::numeric, 2),
  ('Chili frisch', 'Stück', 10::numeric, 1),
  ('Petersilie frisch', 'Bund', 30::numeric, 1),
  ('Petersilie frisch', 'EL', 4::numeric, 2),
  ('Basilikum frisch', 'Bund', 25::numeric, 1),
  ('Basilikum frisch', 'EL', 3::numeric, 2),
  ('Schnittlauch', 'Bund', 25::numeric, 1),
  ('Schnittlauch', 'EL', 3::numeric, 2),
  ('Koriander frisch', 'Bund', 30::numeric, 1),
  ('Dill frisch', 'Bund', 20::numeric, 1),
  ('Minze frisch', 'Bund', 20::numeric, 1),
  ('Grüne Bohnen', 'Hand voll', 100::numeric, 1),
  ('Rosenkohl', 'Stück', 15::numeric, 1),
  ('Kohlrabi', 'Stück', 250::numeric, 1),
  ('Weißkohl', 'Kopf', 1000::numeric, 1),
  ('Spitzkohl', 'Kopf', 800::numeric, 1),
  ('Rotkohl', 'Kopf', 1000::numeric, 1),
  ('Wirsing', 'Kopf', 800::numeric, 1),
  ('Mangold', 'Bund', 250::numeric, 1),
  ('Fenchel', 'Knolle', 300::numeric, 1),
  ('Radieschen', 'Bund', 200::numeric, 1),
  ('Radieschen', 'Stück', 10::numeric, 2),

  -- Brot & Backwaren: Stück-Gewichte als g-Alias (für Nährwert-Schätzung)
  ('Vollkornbrot', 'Scheibe', 40::numeric, 1),
  ('Weißbrot', 'Scheibe', 30::numeric, 1),
  ('Toastbrot', 'Scheibe', 25::numeric, 1),
  ('Baguette', 'Stück', 250::numeric, 1),

  -- Milch & Sahne in ml: TL/EL/Tasse
  ('Milch 1.5%', 'TL', 5::numeric, 1),
  ('Milch 1.5%', 'EL', 15::numeric, 2),
  ('Milch 1.5%', 'Tasse', 200::numeric, 3),
  ('Milch 3.5%', 'TL', 5::numeric, 1),
  ('Milch 3.5%', 'EL', 15::numeric, 2),
  ('Milch 3.5%', 'Tasse', 200::numeric, 3),
  ('Hafermilch', 'TL', 5::numeric, 1),
  ('Hafermilch', 'EL', 15::numeric, 2),
  ('Hafermilch', 'Tasse', 200::numeric, 3),
  ('Sahne', 'TL', 5::numeric, 1),
  ('Sahne', 'EL', 15::numeric, 2),
  ('Sahne', 'Becher', 200::numeric, 3),
  ('Schmand', 'TL', 5::numeric, 1),
  ('Schmand', 'EL', 15::numeric, 2),
  ('Schmand', 'Becher', 200::numeric, 3),
  ('Saure Sahne', 'EL', 15::numeric, 1),
  ('Saure Sahne', 'Becher', 200::numeric, 2),
  ('Crème fraîche', 'TL', 5::numeric, 1),
  ('Crème fraîche', 'EL', 15::numeric, 2),
  ('Crème fraîche', 'Becher', 200::numeric, 3),
  ('Joghurt natur', 'EL', 15::numeric, 1),
  ('Joghurt natur', 'Becher', 250::numeric, 2),
  ('Griechischer Joghurt', 'EL', 15::numeric, 1),
  ('Griechischer Joghurt', 'Becher', 250::numeric, 2),
  ('Skyr', 'EL', 15::numeric, 1),
  ('Skyr', 'Becher', 250::numeric, 2),
  ('Quark mager', 'EL', 15::numeric, 1),
  ('Quark mager', 'Packung', 250::numeric, 2),
  ('Frischkäse', 'TL', 5::numeric, 1),
  ('Frischkäse', 'EL', 15::numeric, 2),
  ('Frischkäse', 'Packung', 200::numeric, 3),
  ('Mozzarella', 'Kugel', 125::numeric, 1),
  ('Parmesan', 'EL', 6::numeric, 1),
  ('Gouda', 'Scheibe', 25::numeric, 1),
  ('Feta', 'Packung', 200::numeric, 1),
  ('Hüttenkäse', 'EL', 15::numeric, 1),
  ('Hüttenkäse', 'Becher', 200::numeric, 2),
  ('Butter', 'TL', 5::numeric, 1),
  ('Butter', 'EL', 15::numeric, 2),
  ('Butter', 'Stück', 250::numeric, 3),
  ('Margarine', 'TL', 5::numeric, 1),
  ('Margarine', 'EL', 15::numeric, 2),

  -- Fleisch & Fisch: Pack/Filet-Gewichte
  ('Hähnchenbrust', 'Filet', 150::numeric, 1),
  ('Putenbrust', 'Filet', 150::numeric, 1),
  ('Schweinefilet', 'Stück', 400::numeric, 1),
  ('Speck', 'Scheibe', 10::numeric, 1),
  ('Schinken gekocht', 'Scheibe', 15::numeric, 1),
  ('Salami', 'Scheibe', 5::numeric, 1),
  ('Bratwurst', 'Stück', 100::numeric, 1),
  ('Lachs frisch', 'Filet', 150::numeric, 1),
  ('Forelle', 'Stück', 250::numeric, 1),
  ('Kabeljau', 'Filet', 150::numeric, 1),

  -- Trockenwaren: Mehl/Zucker → TL/EL/Tasse, Reis/Pasta → Tasse
  ('Spaghetti', 'Portion', 100::numeric, 1),
  ('Penne', 'Portion', 100::numeric, 1),
  ('Fusilli', 'Portion', 100::numeric, 1),
  ('Tagliatelle', 'Portion', 100::numeric, 1),
  ('Reis weiß', 'Portion', 75::numeric, 1),
  ('Reis weiß', 'Tasse', 180::numeric, 2),
  ('Basmatireis', 'Portion', 75::numeric, 1),
  ('Basmatireis', 'Tasse', 180::numeric, 2),
  ('Vollkornreis', 'Portion', 75::numeric, 1),
  ('Risottoreis', 'Portion', 75::numeric, 1),
  ('Couscous', 'Portion', 70::numeric, 1),
  ('Bulgur', 'Portion', 70::numeric, 1),
  ('Quinoa', 'Portion', 70::numeric, 1),
  ('Linsen rot', 'Portion', 80::numeric, 1),
  ('Linsen rot', 'Tasse', 200::numeric, 2),
  ('Linsen grün', 'Portion', 80::numeric, 1),
  ('Linsen grün', 'Tasse', 200::numeric, 2),
  ('Kichererbsen Dose', 'Dose', 240::numeric, 1),
  ('Kidneybohnen Dose', 'Dose', 240::numeric, 1),
  ('Weiße Bohnen Dose', 'Dose', 240::numeric, 1),
  ('Weizenmehl', 'TL', 3::numeric, 1),
  ('Weizenmehl', 'EL', 10::numeric, 2),
  ('Weizenmehl', 'Tasse', 130::numeric, 3),
  ('Dinkelmehl', 'TL', 3::numeric, 1),
  ('Dinkelmehl', 'EL', 10::numeric, 2),
  ('Dinkelmehl', 'Tasse', 130::numeric, 3),
  ('Vollkornmehl', 'TL', 3::numeric, 1),
  ('Vollkornmehl', 'EL', 10::numeric, 2),
  ('Vollkornmehl', 'Tasse', 130::numeric, 3),
  ('Haferflocken', 'EL', 10::numeric, 1),
  ('Haferflocken', 'Tasse', 80::numeric, 2),
  ('Zucker', 'TL', 4::numeric, 1),
  ('Zucker', 'EL', 12::numeric, 2),
  ('Zucker', 'Tasse', 200::numeric, 3),
  ('Zucker', 'Prise', 0.5::numeric, 4),
  ('Brauner Zucker', 'TL', 4::numeric, 1),
  ('Brauner Zucker', 'EL', 12::numeric, 2),
  ('Honig', 'TL', 7::numeric, 1),
  ('Honig', 'EL', 21::numeric, 2),
  ('Ahornsirup', 'TL', 7::numeric, 1),
  ('Ahornsirup', 'EL', 21::numeric, 2),
  ('Backpulver', 'TL', 4::numeric, 1),
  ('Backpulver', 'Päckchen', 16::numeric, 2),
  ('Trockenhefe', 'TL', 3::numeric, 1),
  ('Trockenhefe', 'Päckchen', 7::numeric, 2),
  ('Tomaten passiert', 'Packung', 500::numeric, 1),
  ('Tomaten gehackt Dose', 'Dose', 400::numeric, 1),
  ('Tomatenmark', 'TL', 5::numeric, 1),
  ('Tomatenmark', 'EL', 15::numeric, 2),
  ('Tomatenmark', 'Tube', 200::numeric, 3),
  ('Kokosmilch', 'Dose', 400::numeric, 1),
  ('Kokosmilch', 'EL', 15::numeric, 2),
  ('Senf', 'TL', 5::numeric, 1),
  ('Senf', 'EL', 15::numeric, 2),
  ('Mayonnaise', 'TL', 5::numeric, 1),
  ('Mayonnaise', 'EL', 15::numeric, 2),
  ('Ketchup', 'TL', 5::numeric, 1),
  ('Ketchup', 'EL', 15::numeric, 2),
  ('Sojasauce', 'TL', 5::numeric, 1),
  ('Sojasauce', 'EL', 15::numeric, 2),
  ('Balsamico', 'TL', 5::numeric, 1),
  ('Balsamico', 'EL', 15::numeric, 2),
  ('Apfelessig', 'TL', 5::numeric, 1),
  ('Apfelessig', 'EL', 15::numeric, 2),
  ('Erdnussbutter', 'TL', 8::numeric, 1),
  ('Erdnussbutter', 'EL', 16::numeric, 2),
  ('Cashewkerne', 'EL', 10::numeric, 1),
  ('Cashewkerne', 'Hand voll', 30::numeric, 2),
  ('Walnüsse', 'EL', 8::numeric, 1),
  ('Walnüsse', 'Hand voll', 30::numeric, 2),
  ('Mandeln', 'EL', 10::numeric, 1),
  ('Mandeln', 'Hand voll', 30::numeric, 2),
  ('Pinienkerne', 'EL', 8::numeric, 1),
  ('Sonnenblumenkerne', 'EL', 8::numeric, 1),
  ('Kürbiskerne', 'EL', 8::numeric, 1),
  ('Sesam', 'TL', 3::numeric, 1),
  ('Sesam', 'EL', 9::numeric, 2),
  ('Tofu natur', 'Packung', 200::numeric, 1),
  ('Räuchertofu', 'Packung', 200::numeric, 1),

  -- Gewürze & Öle
  ('Olivenöl', 'TL', 5::numeric, 1),
  ('Olivenöl', 'EL', 15::numeric, 2),
  ('Sonnenblumenöl', 'TL', 5::numeric, 1),
  ('Sonnenblumenöl', 'EL', 15::numeric, 2),
  ('Rapsöl', 'TL', 5::numeric, 1),
  ('Rapsöl', 'EL', 15::numeric, 2),
  ('Sesamöl', 'TL', 5::numeric, 1),
  ('Sesamöl', 'EL', 15::numeric, 2),
  ('Kokosöl', 'TL', 5::numeric, 1),
  ('Kokosöl', 'EL', 15::numeric, 2),
  ('Salz', 'Prise', 0.5::numeric, 1),
  ('Salz', 'TL', 5::numeric, 2),
  ('Salz', 'EL', 15::numeric, 3),
  ('Pfeffer', 'Prise', 0.3::numeric, 1),
  ('Pfeffer', 'TL', 2::numeric, 2),
  ('Pfeffer', 'EL', 6::numeric, 3),
  ('Paprikapulver edelsüß', 'TL', 2.5::numeric, 1),
  ('Paprikapulver edelsüß', 'EL', 7.5::numeric, 2),
  ('Currypulver', 'TL', 2.5::numeric, 1),
  ('Currypulver', 'EL', 7.5::numeric, 2),
  ('Kreuzkümmel', 'TL', 2::numeric, 1),
  ('Kreuzkümmel', 'EL', 6::numeric, 2),
  ('Koriander gemahlen', 'TL', 2::numeric, 1),
  ('Koriander gemahlen', 'EL', 6::numeric, 2),
  ('Zimt', 'TL', 2::numeric, 1),
  ('Zimt', 'EL', 6::numeric, 2),
  ('Muskatnuss', 'Prise', 0.3::numeric, 1),
  ('Muskatnuss', 'TL', 2::numeric, 2),
  ('Kurkuma', 'TL', 2::numeric, 1),
  ('Kurkuma', 'EL', 6::numeric, 2),
  ('Oregano', 'TL', 1::numeric, 1),
  ('Oregano', 'EL', 3::numeric, 2),
  ('Thymian', 'TL', 1::numeric, 1),
  ('Thymian', 'EL', 3::numeric, 2),
  ('Rosmarin', 'TL', 1::numeric, 1),
  ('Rosmarin', 'EL', 3::numeric, 2),
  ('Italienische Kräuter', 'TL', 1::numeric, 1),
  ('Italienische Kräuter', 'EL', 3::numeric, 2),
  ('Chiliflocken', 'Prise', 0.3::numeric, 1),
  ('Chiliflocken', 'TL', 2::numeric, 2),
  ('Vanillezucker', 'Päckchen', 8::numeric, 1),
  ('Vanillezucker', 'TL', 3::numeric, 2),

  -- Sonstiges
  ('Zartbitterschokolade', 'Tafel', 100::numeric, 1),
  ('Zartbitterschokolade', 'Stück', 5::numeric, 2),
  ('Vollmilchschokolade', 'Tafel', 100::numeric, 1),
  ('Vollmilchschokolade', 'Stück', 5::numeric, 2),
  ('Kakao', 'TL', 3::numeric, 1),
  ('Kakao', 'EL', 9::numeric, 2)
)
insert into ingredient_units (ingredient_id, label, factor, sort_order)
select i.id, m.label, m.factor, m.sort_order
from mapping m
join ingredients i on i.name = m.name
on conflict (ingredient_id, label) do nothing;
